import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { FinancialMetrics } from "@/lib/finance/types";
import { analyzeLiquidity } from "@/lib/finance/intelligence/liquidity";
import { formatCurrency } from "@/lib/currency/formatCurrency";

export function generateCashFlowReportPdf({
  investorName,
  companyName,
  founderName,
  metrics,
  currency = "USD",
}: {
  investorName: string;
  companyName: string;
  founderName: string;
  metrics: FinancialMetrics;
  currency?: string;
}) {
  const doc = new jsPDF();
  const generatedAt = new Date().toLocaleDateString();
  const liquidityInsight = analyzeLiquidity(metrics);

  const money = (value: number | string | null | undefined) =>
    formatCurrency(value, currency);

  doc.setTextColor(8, 47, 73);
  doc.setFontSize(12);
  doc.text("HELIX FINANCIAL OS", 14, 18);

  doc.setTextColor(2, 6, 7);
  doc.setFontSize(22);
  doc.text("Cash Flow & Liquidity Report", 14, 32);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Company: ${companyName}`, 14, 42);
  doc.text(`Prepared for: ${investorName}`, 14, 48);
  doc.text(`Founder: ${founderName}`, 14, 54);
  doc.text(`Generated: ${generatedAt}`, 14, 60);

  autoTable(doc, {
    startY: 72,
    head: [["Liquidity Metric", "Value"]],
    body: [
      ["Estimated Cash Position", money(metrics.cashBalance)],
      ["Cash Inflows", money(metrics.cashInflows)],
      ["Cash Outflows", `-${money(metrics.cashOutflows)}`],
      ["Monthly Burn Rate", `${money(metrics.burnRate)} / month`],
      ["Cash Runway", formatRunway(metrics.cashRunwayMonths)],
    ],
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 14,
    head: [["Liquidity Intelligence", "Insight"]],
    body: [
      ["Liquidity Status", liquidityInsight.liquidityStatus],
      ["Risk Level", liquidityInsight.riskLevel],
      ["Cash Runway", formatRunway(metrics.cashRunwayMonths)],
      ["Business Health Score", `${metrics.businessHealthScore}/100`],
    ],
  });

  const nextY = (doc as any).lastAutoTable.finalY + 16;

  doc.setFontSize(13);
  doc.setTextColor(2, 6, 7);
  doc.text("CFO Liquidity Analysis", 14, nextY);

  doc.setFontSize(10);
  doc.setTextColor(70, 70, 70);

  doc.text(doc.splitTextToSize(liquidityInsight.summary, 180), 14, nextY + 10);

  doc.text(
    doc.splitTextToSize(`Recommendation: ${liquidityInsight.recommendation}`, 180),
    14,
    nextY + 28
  );

  footer(doc, companyName);

  doc.save(`${slug(companyName)}-cash-flow-report.pdf`);
}

function formatRunway(months: number | null) {
  if (months === null) return "No current burn";
  if (months >= 120) return "No immediate liquidity risk";
  if (months >= 24) return `${months.toFixed(0)} months`;
  return `${months.toFixed(1)} months`;
}

function footer(doc: jsPDF, companyName: string) {
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.text(`Generated by Helix Financial OS · ${companyName}`, 14, 287);
}

function slug(value: string) {
  return value.toLowerCase().replaceAll(" ", "-");
}