import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { FinancialMetrics } from "@/lib/finance/types";
import { formatCurrency } from "@/lib/currency/formatCurrency";

export function generateInvestorReportPdf({
  investorName,
  companyName,
  founderName,
  metrics,
  currency = "USD",
}: {
  investorName: string;
  companyName: string;
  founderName: string;
  metrics: FinancialMetrics;
  currency?: string;
}) {
  const doc = new jsPDF();
  const generatedAt = new Date().toLocaleDateString();

  const money = (value: number | string | null | undefined) =>
    formatCurrency(value, currency);

  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, 210, 297, "F");

  doc.setDrawColor(103, 232, 249);
  doc.setLineWidth(0.8);
  doc.line(20, 30, 190, 30);

  doc.setTextColor(8, 47, 73);
  doc.setFontSize(12);
  doc.text("HELIX FINANCIAL OS", 20, 42);

  doc.setTextColor(2, 6, 7);
  doc.setFontSize(28);
  doc.text("Investor Financial Report", 20, 62);

  doc.setFontSize(15);
  doc.text(companyName, 20, 82);

  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);
  doc.text(`Prepared for: ${investorName}`, 20, 105);
  doc.text(`Founder: ${founderName}`, 20, 112);
  doc.text(`Generated: ${generatedAt}`, 20, 119);
  doc.text("Confidential investor document", 20, 132);

  doc.setDrawColor(220, 220, 220);
  doc.line(20, 145, 190, 145);

  doc.setTextColor(110, 110, 110);
  doc.setFontSize(9);
  doc.text(
    "This report is generated from live company financial data inside Helix.",
    20,
    158
  );

  doc.addPage();

  sectionTitle(doc, "Executive Summary", 20);

  const summary = buildExecutiveSummary(metrics, currency);

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(doc.splitTextToSize(summary, 175), 14, 32);

  autoTable(doc, {
    startY: 70,
    head: [["Key Metric", "Value"]],
    body: [
      ["Revenue", money(metrics.revenue)],
      ["Gross Profit", money(metrics.grossProfit)],
      ["Net Profit", money(metrics.netProfit)],
      ["Gross Margin", `${metrics.grossMargin.toFixed(1)}%`],
      ["Net Margin", `${metrics.netMargin.toFixed(1)}%`],
      ["Business Health Score", `${metrics.businessHealthScore}/100`],
    ],
  });

  doc.addPage();
  sectionTitle(doc, "Profit & Loss", 20);

  autoTable(doc, {
    startY: 32,
    head: [["Line Item", "Amount"]],
    body: [
      ["Revenue", money(metrics.revenue)],
      ["Cost of Goods Sold", `-${money(metrics.cogs)}`],
      ["Gross Profit", money(metrics.grossProfit)],
      ["Operating Expenses", `-${money(metrics.expenses)}`],
      ["EBITDA Estimate", money(metrics.ebitda)],
      ["Net Profit", money(metrics.netProfit)],
    ],
  });

  sectionTitle(doc, "Liquidity & Cash Position", 125);

  autoTable(doc, {
    startY: 137,
    head: [["Metric", "Value"]],
    body: [
      ["Estimated Cash Position", money(metrics.cashBalance)],
      ["Cash Inflows", money(metrics.cashInflows)],
      ["Cash Outflows", money(metrics.cashOutflows)],
      ["Monthly Burn Rate", `${money(metrics.burnRate)} / month`],
      ["Cash Runway", formatRunway(metrics.cashRunwayMonths)],
    ],
  });

  doc.addPage();
  sectionTitle(doc, "Investment & Valuation", 20);

  autoTable(doc, {
    startY: 32,
    head: [["Metric", "Value"]],
    body: [
      ["Total Investment", money(metrics.totalInvestment)],
      ["Equity Owned", `${metrics.equityPercent.toFixed(2)}%`],
      ["Estimated Company Valuation", money(metrics.companyValuation)],
      ["Estimated Equity Value", money(metrics.equityValue)],
      ["Estimated ROI", `${metrics.roi.toFixed(1)}%`],
    ],
  });

  sectionTitle(doc, "Risk Assessment", 130);

  autoTable(doc, {
    startY: 142,
    head: [["Area", "Status"]],
    body: [
      [
        "Liquidity Risk",
        metrics.cashRunwayMonths === null || metrics.cashRunwayMonths > 12
          ? "Low"
          : "Needs attention",
      ],
      ["Profitability", metrics.netProfit > 0 ? "Healthy" : "Negative"],
      [
        "Inventory Efficiency",
        metrics.inventoryTurnover && metrics.inventoryTurnover >= 1
          ? "Stable"
          : "Needs review",
      ],
      ["Overall Health", getHealthLabel(metrics.businessHealthScore)],
    ],
  });

  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text(`Generated by Helix Financial OS · ${companyName}`, 14, 287);
    doc.text(`Page ${i} of ${pageCount}`, 180, 287);
  }

  doc.save(`${companyName.toLowerCase().replaceAll(" ", "-")}-investor-report.pdf`);
}

function sectionTitle(doc: jsPDF, title: string, y: number) {
  doc.setFontSize(16);
  doc.setTextColor(2, 6, 7);
  doc.text(title, 14, y);
}

function buildExecutiveSummary(metrics: FinancialMetrics, currency: string) {
  const money = (value: number | string | null | undefined) =>
    formatCurrency(value, currency);

  return `The company generated ${money(metrics.revenue)} in revenue with gross profit of ${money(
    metrics.grossProfit
  )} and net profit of ${money(metrics.netProfit)}. Gross margin is ${metrics.grossMargin.toFixed(
    1
  )}% and net margin is ${metrics.netMargin.toFixed(
    1
  )}%. Estimated cash position is ${money(
    metrics.cashBalance
  )}, with monthly burn rate of ${money(metrics.burnRate)}. Cash runway is ${formatRunway(
    metrics.cashRunwayMonths
  )}. Estimated company valuation is ${money(
    metrics.companyValuation
  )}, giving the investor equity an estimated value of ${money(
    metrics.equityValue
  )}. Overall business health is ${metrics.businessHealthScore}/100, rated ${getHealthLabel(
    metrics.businessHealthScore
  )}.`;
}

function formatRunway(months: number | null) {
  if (months === null) return "No current burn";
  if (months >= 120) return "No immediate liquidity risk";
  if (months >= 24) return `${months.toFixed(0)} months`;
  return `${months.toFixed(1)} months`;
}

function getHealthLabel(score: number) {
  if (score >= 85) return "Excellent";
  if (score >= 70) return "Strong";
  if (score >= 50) return "Stable";
  if (score >= 30) return "Needs attention";
  return "High risk";
}