import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { FinancialMetrics } from "@/lib/finance/types";
import { analyzeInventory } from "@/lib/finance/intelligence/inventory";
import { formatCurrency } from "@/lib/currency/formatCurrency";

export function generateInventoryReportPdf({
  investorName,
  companyName,
  founderName,
  metrics,
  currency = "USD",
}: {
  investorName: string;
  companyName: string;
  founderName: string;
  metrics: FinancialMetrics;
  currency?: string;
}) {
  const doc = new jsPDF();
  const generatedAt = new Date().toLocaleDateString();
  const inventoryInsight = analyzeInventory(metrics);

  const money = (value: number | string | null | undefined) =>
    formatCurrency(value, currency);

  doc.setTextColor(8, 47, 73);
  doc.setFontSize(12);
  doc.text("HELIX FINANCIAL OS", 14, 18);

  doc.setTextColor(2, 6, 7);
  doc.setFontSize(22);
  doc.text("Inventory Valuation Report", 14, 32);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Company: ${companyName}`, 14, 42);
  doc.text(`Prepared for: ${investorName}`, 14, 48);
  doc.text(`Founder: ${founderName}`, 14, 54);
  doc.text(`Generated: ${generatedAt}`, 14, 60);

  autoTable(doc, {
    startY: 72,
    head: [["Inventory Metric", "Value"]],
    body: [
      ["Inventory Value", money(metrics.inventoryValue)],
      ["Cost of Goods Sold", money(metrics.cogs)],
      [
        "Inventory Turnover",
        metrics.inventoryTurnover === null
          ? "Not enough data"
          : `${metrics.inventoryTurnover.toFixed(2)}x`,
      ],
      ["Gross Profit", money(metrics.grossProfit)],
      ["Gross Margin", `${metrics.grossMargin.toFixed(1)}%`],
    ],
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 14,
    head: [["Inventory Intelligence", "Insight"]],
    body: [
      ["Turnover Status", inventoryInsight.turnoverStatus],
      ["Risk Level", inventoryInsight.riskLevel],
      [
        "Days Inventory Outstanding",
        inventoryInsight.daysInventoryOutstanding === null
          ? "Not enough data"
          : `${inventoryInsight.daysInventoryOutstanding.toFixed(0)} days`,
      ],
      ["Business Health Score", `${metrics.businessHealthScore}/100`],
    ],
  });

  const nextY = (doc as any).lastAutoTable.finalY + 16;

  doc.setFontSize(13);
  doc.setTextColor(2, 6, 7);
  doc.text("CFO Inventory Analysis", 14, nextY);

  doc.setFontSize(10);
  doc.setTextColor(70, 70, 70);

  doc.text(doc.splitTextToSize(inventoryInsight.summary, 180), 14, nextY + 10);

  doc.text(
    doc.splitTextToSize(`Recommendation: ${inventoryInsight.recommendation}`, 180),
    14,
    nextY + 28
  );

  footer(doc, companyName);

  doc.save(`${slug(companyName)}-inventory-valuation-report.pdf`);
}

function footer(doc: jsPDF, companyName: string) {
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.text(`Generated by Helix Financial OS · ${companyName}`, 14, 287);
}

function slug(value: string) {
  return value.toLowerCase().replaceAll(" ", "-");
}