import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { FinancialMetrics } from "@/lib/finance/types";
import { analyzeProfitability } from "@/lib/finance/intelligence/profitability";
import { formatCurrency } from "@/lib/currency/formatCurrency";

export function generateProfitLossReportPdf({
  investorName,
  companyName,
  founderName,
  metrics,
  currency = "USD",
}: {
  investorName: string;
  companyName: string;
  founderName: string;
  metrics: FinancialMetrics;
  currency?: string;
}) {
  const doc = new jsPDF();
  const generatedAt = new Date().toLocaleDateString();
  const profitabilityInsight = analyzeProfitability(metrics);

  const money = (value: number | string | null | undefined) =>
    formatCurrency(value, currency);

  doc.setTextColor(8, 47, 73);
  doc.setFontSize(12);
  doc.text("HELIX FINANCIAL OS", 14, 18);

  doc.setTextColor(2, 6, 7);
  doc.setFontSize(22);
  doc.text("Profit & Loss Report", 14, 32);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Company: ${companyName}`, 14, 42);
  doc.text(`Prepared for: ${investorName}`, 14, 48);
  doc.text(`Founder: ${founderName}`, 14, 54);
  doc.text(`Generated: ${generatedAt}`, 14, 60);

  autoTable(doc, {
    startY: 72,
    head: [["Profit & Loss", "Amount"]],
    body: [
      ["Revenue", money(metrics.revenue)],
      ["Cost of Goods Sold", `-${money(metrics.cogs)}`],
      ["Gross Profit", money(metrics.grossProfit)],
      ["Operating Expenses", `-${money(metrics.expenses)}`],
      ["EBITDA Estimate", money(metrics.ebitda)],
      ["Net Profit", money(metrics.netProfit)],
    ],
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 14,
    head: [["Margins", "Value"]],
    body: [
      ["Gross Margin", `${metrics.grossMargin.toFixed(1)}%`],
      ["Net Margin", `${metrics.netMargin.toFixed(1)}%`],
    ],
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 14,
    head: [["Profitability Intelligence", "Insight"]],
    body: [
      ["Profitability Status", profitabilityInsight.profitabilityStatus],
      ["Risk Level", profitabilityInsight.riskLevel],
      ["Gross Margin", `${metrics.grossMargin.toFixed(1)}%`],
      ["Net Margin", `${metrics.netMargin.toFixed(1)}%`],
    ],
  });

  const nextY = (doc as any).lastAutoTable.finalY + 16;

  doc.setFontSize(13);
  doc.setTextColor(2, 6, 7);
  doc.text("CFO Profitability Analysis", 14, nextY);

  doc.setFontSize(10);
  doc.setTextColor(70, 70, 70);

  doc.text(
    doc.splitTextToSize(profitabilityInsight.summary, 180),
    14,
    nextY + 10
  );

  doc.text(
    doc.splitTextToSize(
      `Recommendation: ${profitabilityInsight.recommendation}`,
      180
    ),
    14,
    nextY + 28
  );

  footer(doc, companyName);

  doc.save(`${slug(companyName)}-profit-loss-report.pdf`);
}

function footer(doc: jsPDF, companyName: string) {
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.text(`Generated by Helix Financial OS · ${companyName}`, 14, 287);
}

function slug(value: string) {
  return value.toLowerCase().replaceAll(" ", "-");
}